# This files generates all intermediate files and combine them into one executatble file



# Syntax: make   OR
#         make all


# to remove all intermediate files
# Syntax: make clean

# compiler to be used. Here it is 'gcc'.
$(CC) = gcc

# default target which will be executed at first by default
all: SpellAnalyzer


# SpellAnalyzer is name given for executables that will be generated by command mentioned below.
# dictionary.o prefix.o spell.o main.o files are its dependencies
SpellAnalyzer: dictionary.o prefix.o spell.o main.o
	$(CC) dictionary.o prefix.o spell.o main.o -o SpellAnalyzer

dictionary.o: dictionary.c
	$(CC) -c dictionary.c

prefix.o: prefix.c 
	$(CC) -c prefix.c

spell.o: spell.c 
	$(CC) -c spell.c

main.o: main.c dictionary.h
	$(CC) -c main.c


# target to clean / remove all intermediate and executables files generated 
clean:
	rm -rf *.o SpellAnalyzer